[project]
name = "lostark-battlepoint-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.7"
dependencies = [
    "jmespath>=1.0.1",
    "numpy>=2.2.6",
    "requests>=2.32.4",
]
